services:
  # Apache + PHP Server
  web:
    build: .
    container_name: running_notes_web
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  # MySQL DB
  db:
    image: mysql:9.0
    container_name: running_notes_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: running_notes #
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: